### ISSUE TITLE
Practica 5 - Control personalizado

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Heidi-19#2]
Reporte de practica 5 
[Practica 5 - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Heidi-19/files/8332281/Practica.5.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
